### ISSUE TITLE
Builder.py relies on specific directory layouts

### ISSUE THREAD

**Issue by linuxwolf** [xsf/xsf-tools#2]
Builder.py makes some assumptions about the directory layout from where it's run.  The most obvious is that it looks for "../images/xmpp.pdf" and "../images/xmpp-text.pdf".  There might be more, but nothing as obvious.

Recommend that it parameterize the location somehow.

**Comment by imaginator** [comment]
This problem is currently impacting the xmpp.org website building. Any objections to this fix being merged in?

**Comment by winfried** [comment]
Merged in, with some additions
